name: Deploy to AWS S3 and Invalidate CloudFront

on: 
  push:
    branches: [ "main" ] # main 브랜치에 push될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # 1. 저장소 체크아웃
      - uses: actions/checkout@v3

      # 2. Node.js 환경 세팅
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. 빌드 실행 (Vite → dist/ 폴더 생성)
      - name: Build
        run: npm run build

      # 5. AWS 인증
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6. S3 업로드
      - name: Deploy to S3
        run: aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete

      # 7. CloudFront 캐시 무효화
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} \
          --paths "/*"
